apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: mysql:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: employee-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            value: "employeemanager"
          - name: MYSQL_USER
            valueFrom: 
              secretKeyRef: 
                name: employee-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: employee-secret
                key: MYSQL_PASSWORD
      volumes:  # This is a key part that was missing
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc     
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysqldb 
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306



