apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: ahmedamin1998/myapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
                name: employee-configmap
                key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom: 
              secretKeyRef: 
                name: employee-secret
                key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: employee-secret
              key: MYSQL_PASSWORD
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.MySQL5Dialect"
        - name: CORS_FILTER
          valueFrom:
            configMapKeyRef:
              name: employee-configmap
              key: API_BASE_URL     
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080


